export const products = [
  // Miere (Honey)
  {
    id: 'prod1',
    name: 'Miere de Salcâm',
    category: 'miere',
    price: 180,
    unit: 'kg',
    description: 'Mierea de salcâm este recunoscută pentru culoarea sa deschisă și proprietatea de a nu cristaliza rapid. Are un gust delicat și ușor floral.',
    image: '/assets/productsImgs/miere/miere_de_salcam.jpeg',
  },
  {
    id: 'prod2',
    name: 'Miere de Coriandru',
    category: 'miere',
    price: 150,
    unit: 'kg',
    description: 'Mierea de coriandru are o aromă distinctivă și un gust ușor picant. Este bogată în antioxidanți și are proprietăți antibacteriene.',
    image: '/assets/productsImgs/miere/miere_de_coriandru.jpeg',
  },
  {
    id: 'prod3',
    name: 'Miere de Floarea-Soarelui',
    category: 'miere',
    price: 100,
    unit: 'kg',
    description: 'Mierea de floarea-soarelui este una dintre cele mai populare soiuri de miere. Are o culoare aurie și un gust dulce și parfumat.',
    image: '/assets/productsImgs/miere/miere_de_floarea_soarelui.jpeg',
  },
  // Fagure (Honeycomb)
  {
    id: 'prod4',
    name: 'Fagure în ramă',
    category: 'fagure',
    price: 250,
    unit: 'bucata',
    description: 'Fagurul în ramă este un produs natural și delicios. Este o sursa excelentă de vitamine și minerale.',
    image: '/assets/productsImgs/fagure/fagure.jpeg',
  },
  {
    id: 'prod5',
    name: 'Fagure cu Miere',
    category: 'fagure',
    price: 150,
    unit: 'borcan',
    description: 'Fagurele cu miere este un produs tradițional și delicios. Este o combinație perfectă de miere și ceară de albine.',
    image: '/assets/productsImgs/fagure/fagureborcan.jpeg',
  },
  {
    id: 'prod6',
    name: 'Fagure Mic',
    category: 'fagure',
    price: 50,
    unit: 'bucata',
    description: 'Fagurele mic este un produs natural și delicios. Este o sursa excelentă de vitamine și minerale.',
    image: '/assets/productsImgs/fagure/faguremic.jpeg',
  },
  // Lumânări (Candles)
  {
    id: 'prod7',
    name: 'Lumânări din ceară (10cm)',
    category: 'lumanari',
    price: 50,
    unit: 'bucata',
    description: 'Lumânările din ceară de albine sunt produse naturale și ecologice. Acestea ard mai lent decât lumânările din parafină și au o aromă naturală de miere.',
    image: '/assets/productsImgs/lumanari/lumanari.jpeg',
  },
  {
    id: 'prod8',
    name: 'Lumânări din ceară (15cm)',
    category: 'lumanari',
    price: 65,
    unit: 'bucata',
    description: 'Lumânările din ceară de albine sunt produse naturale și ecologice. Acestea ard mai lent decât lumânările din parafină și au o aromă naturală de miere.',
    image: '/assets/productsImgs/lumanari/lumanari.jpeg',
  },
  {
    id: 'prod9',
    name: 'Lumânări din ceară (20cm)',
    category: 'lumanari',
    price: 70,
    unit: 'bucata',
    description: 'Lumânările din ceară de albine sunt produse naturale și ecologice. Acestea ard mai lent decât lumânările din parafină și au o aromă naturală de miere.',
    image: '/assets/productsImgs/lumanari/lumanari.jpeg',
  },
  // Polen (Pollen)
  {
    id: 'prod10',
    name: 'Polen în Borcan',
    category: 'polen',
    price: 100,
    unit: 'borcan',
    description: 'Polenul în borcan este un produs natural și delicios. Este o sursa excelentă de vitamine și minerale.',
    image: '/assets/productsImgs/polen/polenborcan2.jpeg',
  },
  {
    id: 'prod11',
    name: 'Polen cu Miere',
    category: 'polen',
    price: 150,
    unit: 'borcan',
    description: 'Polenul cu miere este un produs natural și delicios. Este o combinație perfectă de miere și polen.',
    image: '/assets/productsImgs/polen/polencumiere.jpeg',
  },
  {
    id: 'prod12',
    name: 'Polen în Caserolă',
    category: 'polen',
    price: 50,
    unit: '100g',
    description: 'Polenul în caserolă este un produs natural și delicios. Este o sursa excelentă de vitamine și minerale.',
    image: '/assets/productsImgs/polen/polencaserola.jpeg',
  },
]

export const categories = [
  { id: 'all', label: 'Toate' },
  { id: 'miere', label: 'Miere' },
  { id: 'fagure', label: 'Fagure' },
  { id: 'lumanari', label: 'Lumânări' },
  { id: 'polen', label: 'Polen' },
]

export const featuredProductIds = ['prod1', 'prod2', 'prod4', 'prod10', 'prod7']
